import React, { useState } from 'react';
import { SavedOutfit, ActiveTab } from '../types.js';
import { deleteSavedOutfit } from '../api.js';
import { OutfitCard } from './OutfitCard.js';
import { Bookmark, Trash2, ArrowRight, Sparkles, Calendar } from 'lucide-react';

interface SavedOutfitsViewProps {
  savedOutfits: SavedOutfit[];
  onSavedOutfitsUpdated: (updated: SavedOutfit[]) => void;
  userId: string;
  setActiveTab: (tab: ActiveTab) => void;
  onFeedback: (outfitId: string, outfitTitle: string, type: 'like' | 'dislike') => Promise<void>;
}

export const SavedOutfitsView: React.FC<SavedOutfitsViewProps> = ({
  savedOutfits,
  onSavedOutfitsUpdated,
  userId,
  setActiveTab,
  onFeedback,
}) => {
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const handleDelete = async (savedId: string) => {
    if (!confirm('Remove this outfit from your saved collection?')) return;
    try {
      setDeletingId(savedId);
      const success = await deleteSavedOutfit(savedId, userId);
      if (success) {
        onSavedOutfitsUpdated(savedOutfits.filter((item) => item.id !== savedId));
      }
    } catch (err) {
      console.error('Delete saved outfit error:', err);
    } finally {
      setDeletingId(null);
    }
  };

  return (
    <div className="space-y-8 pb-16">
      {/* Header */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-[#E4EDFF] shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#EEF3FF] border border-[#D6E2FF] text-[#4A6CF7] text-xs font-semibold mb-2">
            <Bookmark className="w-3.5 h-3.5 text-[#E98BAF]" />
            <span>Curated Lookbook</span>
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-bold text-[#20243A]">
            Saved Outfits ({savedOutfits.length})
          </h1>
          <p className="text-xs sm:text-sm text-[#5E6482] mt-1">
            Browse through your saved outfits generated by the AI Stylist or mixed from your virtual wardrobe.
          </p>
        </div>

        <button
          id="saved-open-stylist-btn"
          onClick={() => setActiveTab('stylist')}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#4A6CF7] text-white text-xs font-semibold hover:bg-[#3B5BD8] transition-all shrink-0 shadow-sm"
        >
          <Sparkles className="w-4 h-4 text-[#FFF0F5]" />
          <span>Generate New Outfit</span>
        </button>
      </div>

      {/* Saved Outfits List */}
      {savedOutfits.length === 0 ? (
        <div className="bg-white rounded-3xl p-12 text-center border border-dashed border-[#D6E2FF] space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-[#EEF3FF] text-[#4A6CF7] flex items-center justify-center mx-auto">
            <Bookmark className="w-6 h-6 stroke-1" />
          </div>
          <h3 className="font-display text-xl font-bold text-[#20243A]">
            No Saved Outfits Yet
          </h3>
          <p className="text-xs sm:text-sm text-[#5E6482] max-w-sm mx-auto">
            When you ask the AI Stylist for recommendations or create an outfit from your wardrobe, click the "Save" button to bookmark your favorites here.
          </p>
          <button
            id="empty-go-stylist-btn"
            onClick={() => setActiveTab('stylist')}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#4A6CF7] text-white text-xs font-semibold hover:bg-[#3B5BD8] transition-all shadow-sm"
          >
            <span>Ask AI Stylist for an Outfit</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {savedOutfits.map((saved) => (
            <div key={saved.id} className="relative group flex flex-col">
              <OutfitCard
                outfit={saved.outfit}
                isSaved={true}
                showSaveButton={false}
                onFeedback={onFeedback}
                className="h-full"
              />

              {/* Saved Meta & Delete */}
              <div className="mt-2 px-3 flex items-center justify-between text-xs text-[#5E6482]">
                <div className="flex items-center gap-1.5">
                  <Calendar className="w-3.5 h-3.5 text-[#5E6482]" />
                  <span>Saved on {new Date(saved.savedAt).toLocaleDateString()}</span>
                </div>

                <button
                  id={`delete-saved-${saved.id}`}
                  onClick={() => handleDelete(saved.id)}
                  disabled={deletingId === saved.id}
                  className="flex items-center gap-1 text-[#5E6482] hover:text-rose-600 transition-colors"
                  title="Remove from saved collection"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  <span>Remove</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
